"""empty message

Revision ID: 332cc5fbed2e
Revises: e9a6460722ee
Create Date: 2023-03-13 11:50:59.588951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332cc5fbed2e'
down_revision = 'e9a6460722ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hops', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(length=32), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
