"""empty message

Revision ID: 7476d7a43450
Revises: 
Create Date: 2023-03-07 22:01:54.132649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7476d7a43450'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hops', schema=None) as batch_op:
        batch_op.drop_column('test_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_column', sa.VARCHAR(length=32), nullable=True))

    # ### end Alembic commands ###
