"""Initial migration

Revision ID: b7afac4ec343
Revises: 
Create Date: 2023-02-23 15:27:00.317168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b7afac4ec343'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alpha_max_percentage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('alpha_min_percentage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('beta_max_percentage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('beta_min_percentage', sa.Integer(), nullable=True))
        batch_op.drop_column('beta')
        batch_op.drop_column('alpha')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    with op.batch_alter_table('hops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alpha', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('beta', sqlite.JSON(), nullable=True))
        batch_op.drop_column('beta_min_percentage')
        batch_op.drop_column('beta_max_percentage')
        batch_op.drop_column('alpha_min_percentage')
        batch_op.drop_column('alpha_max_percentage')

    # ### end Alembic commands ###
