"""Hop's beer_styles type change, from JSON to string

Revision ID: c1066a5924a6
Revises: b7afac4ec343
Create Date: 2023-02-23 17:20:38.472428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c1066a5924a6'
down_revision = 'b7afac4ec343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hops', schema=None) as batch_op:
        batch_op.alter_column('beer_styles',
               existing_type=sqlite.JSON(),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hops', schema=None) as batch_op:
        batch_op.alter_column('beer_styles',
               existing_type=sa.String(length=256),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
