"""empty message

Revision ID: cb8a57c4909b
Revises: 7476d7a43450
Create Date: 2023-03-08 09:03:50.692845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8a57c4909b'
down_revision = '7476d7a43450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hops', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
